version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}shopapi
    build:
      context: .
      dockerfile: ShopAPI/Dockerfile

  client:
    image: client
    build:
        context: ./client
        dockerfile: Dockerfile

  proxy:
    image: nginx:mainline
